#!/bin/bash
echo "Para ver el código en la consola del servidor:"
echo ""
echo "1. Ve a la terminal donde corre 'npm run dev'"
echo "2. Verás un mensaje como:"
echo "   📧 [DEV] Código de acceso para dlhernan@uc.cl: 123456"
echo ""
echo "3. O puedes revisar los logs del servidor si están guardados"
echo ""
echo "Para probar ahora, solicita un código desde el frontend"
echo "o ejecuta:"
echo "curl -X POST http://localhost:4000/api/auth/request-code \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"rut\":\"15636274-3\"}'"
